language: objective-c
osx_image: xcode7.3

before_install:
  - gem install slather --no-document --quiet

script:
  - xcodebuild clean build test -workspace FeedHenry.xcworkspace -scheme FeedHenry -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

notifications:
  irc: "irc.freenode.org#feedhenry"

branches:
  only:
    - master
    - 4.1.2

after_success:
  - slather
